### ISSUE TITLE
parser.byteDelimiter bug

### ISSUE THREAD

**Issue by vjpr** [EmergingTechnologyAdvisors/node-serialport#582]
Currently for a match to occur, the delimiters don't have to be consecutive.

This causes an issue when the delimiter sequence is split during buffering.

E.g. 

Raw data from serial port: `$$data$$data$$`
If we receive `$data$$data$` we get `$data$`, instead of just the second `data`.

Simple fix:

```
      if(buf[buf.length-1] === delimiter[nextDelimIndex]) {
        nextDelimIndex++;
      } else if (nextDelimIndex > 0) { // i.e. so far we have a partial match...
        nextDelimIndex = 0
      }
```

**Comment by orgicus** [comment]
Having a similar issue trying to read data from an RFID reader. The packet sent looks like this:

```
0x02 0x30 0x31 0x30 0x45 0x41 0x35 0x38 0x41 0x38  0x33 0x0D 0x0A 0x03
```

but with the default settings I always get two calls with the data split into two strings at different indices each time. I've set the parser to readline:
```
parser: serialPort.parsers.readline(0x03)
```
but I still get the data split into two callbacks. At least this way, the data is split at the same index each time, so I can merge the data as a hacky workaround, but it would be great if this issue could be resolved (and I wouldn't need to rely on hacks).

Also, the data returned in the callback is a String. I assume there might be cases where the raw bytes are needed. Any recommendations on getting raw binary data ?
